# Generated by Django 5.1.4 on 2024-12-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_exercisequestion_mark_question_mark'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='class_shell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentSubmission', to='instructor.classshell'),
        ),
    ]
