# Generated by Django 5.1.4 on 2024-12-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_assignmentsubmission_class_shell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='class_shell',
        ),
    ]
