# Generated by Django 5.1.4 on 2024-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_assignmentsubmission_class_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseattempt',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
