# Generated by Django 5.1.4 on 2024-12-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_exerciseattempt_grade_exerciseattempt_graded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='class_shell',
        ),
    ]
