# Generated by Django 5.1.4 on 2025-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_questionattempt_class_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
