# Generated by Django 5.1.4 on 2025-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_assignmentsubmission_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
