# Generated by Django 5.1.4 on 2025-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_exerciseattempt_end_time_quizattempt_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseattempt',
            name='total_marks',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_marks',
            field=models.FloatField(blank=True),
        ),
    ]
