# Generated by Django 5.1.7 on 2025-11-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_user'),
        ('learning_paths', '0002_remove_learningresource_path_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfeedback',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_paths.topicresource'),
        ),
        migrations.AlterField(
            model_name='pathfeedback',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
    ]
