# Generated by Django 4.2.16 on 2024-09-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_classshell_user_alter_course_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
