# Generated by Django 4.2.16 on 2024-10-27 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0003_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classshell',
            name='students_with_access',
            field=models.ManyToManyField(blank=True, related_name='accessible_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
