# Generated by Django 4.2.16 on 2024-09-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
