# Generated by Django 4.2.16 on 2024-10-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_classshell_students_with_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='is_true',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ExerciseAnswer',
        ),
    ]
