# Generated by Django 4.2.16 on 2024-10-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_remove_exerciseanswer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisequestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
