# Generated by Django 4.2.16 on 2024-10-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_remove_exercisequestion_text_remove_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisequestion',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
