# Generated by Django 4.2.16 on 2024-10-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
            preserve_default=False,
        ),
    ]
