# Generated by Django 4.2.16 on 2024-10-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_rename_question_exercisequestion_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisequestion',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
