# Generated by Django 4.2.16 on 2024-10-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_rename_question_text_exercisequestion_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisequestion',
            name='is_true',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_true',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='mcq_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='tf_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mcq_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tf_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='choice_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='choice_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='choice_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='choice_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
