# Generated by Django 5.1.4 on 2025-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_assignment_due_date_exercise_due_date_quiz_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(default=5),
        ),
    ]
