# Generated by Django 5.1.4 on 2025-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_assignment_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
