# Generated by Django 5.1.4 on 2025-02-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_assignment_max_attempts_exercise_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='timer',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='timer',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
