# Generated by Django 5.1.4 on 2025-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0016_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10),
        ),
    ]
