# Generated by Django 5.1.4 on 2025-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0017_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisequestion',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
