# Generated by Django 5.1.4 on 2025-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0019_remove_exercisequestion_mcq_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisequestion',
            name='choice_1',
        ),
        migrations.RemoveField(
            model_name='exercisequestion',
            name='choice_2',
        ),
        migrations.RemoveField(
            model_name='exercisequestion',
            name='choice_3',
        ),
        migrations.RemoveField(
            model_name='exercisequestion',
            name='choice_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_4',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='mcq_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mcq_choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
